// automatically generated by the FlatBuffers compiler, do not modify

package rooty.road;

@SuppressWarnings("unused")
public final class RoadClass {
  private RoadClass() { }
  public static final byte Unknown = 0;
  public static final byte Motorway = 1;
  public static final byte Trunk = 2;
  public static final byte Primary = 3;
  public static final byte Secondary = 4;
  public static final byte Tertiary = 5;
  public static final byte Service = 6;
  public static final byte Street = 7;
  public static final byte Link = 8;
  public static final byte Path = 9;
  public static final byte Track = 10;

  public static final String[] names = { "Unknown", "Motorway", "Trunk", "Primary", "Secondary", "Tertiary", "Service", "Street", "Link", "Path", "Track", };

  public static String name(int e) { return names[e]; }
}

