// automatically generated by the FlatBuffers compiler, do not modify

package rooty.road;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class RoadFeaturePack extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static RoadFeaturePack getRootAsRoadFeaturePack(ByteBuffer _bb) { return getRootAsRoadFeaturePack(_bb, new RoadFeaturePack()); }
  public static RoadFeaturePack getRootAsRoadFeaturePack(ByteBuffer _bb, RoadFeaturePack obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RoadFeaturePack __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public rooty.road.RoadFeature features(int j) { return features(new rooty.road.RoadFeature(), j); }
  public rooty.road.RoadFeature features(rooty.road.RoadFeature obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int featuresLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public rooty.road.RoadFeature.Vector featuresVector() { return featuresVector(new rooty.road.RoadFeature.Vector()); }
  public rooty.road.RoadFeature.Vector featuresVector(rooty.road.RoadFeature.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createRoadFeaturePack(FlatBufferBuilder builder,
      int featuresOffset) {
    builder.startTable(1);
    RoadFeaturePack.addFeatures(builder, featuresOffset);
    return RoadFeaturePack.endRoadFeaturePack(builder);
  }

  public static void startRoadFeaturePack(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addFeatures(FlatBufferBuilder builder, int featuresOffset) { builder.addOffset(0, featuresOffset, 0); }
  public static int createFeaturesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFeaturesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRoadFeaturePack(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishRoadFeaturePackBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedRoadFeaturePackBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RoadFeaturePack get(int j) { return get(new RoadFeaturePack(), j); }
    public RoadFeaturePack get(RoadFeaturePack obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

