// automatically generated by the FlatBuffers compiler, do not modify

package rooty.road;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class RoadFeature extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static RoadFeature getRootAsRoadFeature(ByteBuffer _bb) { return getRootAsRoadFeature(_bb, new RoadFeature()); }
  public static RoadFeature getRootAsRoadFeature(ByteBuffer _bb, RoadFeature obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RoadFeature __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Flattened coordinates [lng0, lat0, lng1, lat1, ...]
   */
  public double coordinates(int j) { int o = __offset(4); return o != 0 ? bb.getDouble(__vector(o) + j * 8) : 0; }
  public int coordinatesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public DoubleVector coordinatesVector() { return coordinatesVector(new DoubleVector()); }
  public DoubleVector coordinatesVector(DoubleVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer coordinatesAsByteBuffer() { return __vector_as_bytebuffer(4, 8); }
  public ByteBuffer coordinatesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 8); }
  public byte roadClass() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte structureType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  /**
   * Z-level from MVT "layer" property (-1 to 2)
   */
  public byte zLevel() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  /**
   * OSM feature ID (0 = absent)
   */
  public long osmId() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  /**
   * Road reference ID (e.g. "I-95", "M1")
   */
  public String refId() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer refIdAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer refIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }

  public static int createRoadFeature(FlatBufferBuilder builder,
      int coordinatesOffset,
      byte roadClass,
      byte structureType,
      byte zLevel,
      long osmId,
      int refIdOffset) {
    builder.startTable(6);
    RoadFeature.addOsmId(builder, osmId);
    RoadFeature.addRefId(builder, refIdOffset);
    RoadFeature.addCoordinates(builder, coordinatesOffset);
    RoadFeature.addZLevel(builder, zLevel);
    RoadFeature.addStructureType(builder, structureType);
    RoadFeature.addRoadClass(builder, roadClass);
    return RoadFeature.endRoadFeature(builder);
  }

  public static void startRoadFeature(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addCoordinates(FlatBufferBuilder builder, int coordinatesOffset) { builder.addOffset(0, coordinatesOffset, 0); }
  public static int createCoordinatesVector(FlatBufferBuilder builder, double[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addDouble(data[i]); return builder.endVector(); }
  public static void startCoordinatesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static void addRoadClass(FlatBufferBuilder builder, byte roadClass) { builder.addByte(1, roadClass, 0); }
  public static void addStructureType(FlatBufferBuilder builder, byte structureType) { builder.addByte(2, structureType, 0); }
  public static void addZLevel(FlatBufferBuilder builder, byte zLevel) { builder.addByte(3, zLevel, 0); }
  public static void addOsmId(FlatBufferBuilder builder, long osmId) { builder.addLong(4, osmId, 0L); }
  public static void addRefId(FlatBufferBuilder builder, int refIdOffset) { builder.addOffset(5, refIdOffset, 0); }
  public static int endRoadFeature(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RoadFeature get(int j) { return get(new RoadFeature(), j); }
    public RoadFeature get(RoadFeature obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

