// automatically generated by the FlatBuffers compiler, do not modify

package rooty.road;

@SuppressWarnings("unused")
public final class StructureType {
  private StructureType() { }
  public static final byte Road = 0;
  public static final byte Bridge = 1;
  public static final byte Tunnel = 2;

  public static final String[] names = { "Road", "Bridge", "Tunnel", };

  public static String name(int e) { return names[e]; }
}

